/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zilliz_spark_connector_jni_MilvusStorageJNI */

#ifndef _Included_com_zilliz_spark_connector_jni_MilvusStorageJNI
#define _Included_com_zilliz_spark_connector_jni_MilvusStorageJNI
#ifdef __cplusplus
extern "C" {
#endif


// ==================== Reader C API Methods ====================

/*
 * Class:     com_zilliz_spark_connector_jni_MilvusStorageJNI
 * Method:    readPropertiesDefault
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_zilliz_spark_connector_jni_MilvusStorageJNI_00024_readPropertiesDefault
  (JNIEnv *, jclass);

/*
 * Class:     com_zilliz_spark_connector_jni_MilvusStorageJNI
 * Method:    readPropertiesCreate
 * Signature: ([Ljava/lang/String;[Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_zilliz_spark_connector_jni_MilvusStorageJNI_00024_readPropertiesCreate
  (JNIEnv *, jclass, jobjectArray, jobjectArray);

/*
 * Class:     com_zilliz_spark_connector_jni_MilvusStorageJNI
 * Method:    readPropertiesGet
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_zilliz_spark_connector_jni_MilvusStorageJNI_00024_readPropertiesGet
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_zilliz_spark_connector_jni_MilvusStorageJNI
 * Method:    readPropertiesFree
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_zilliz_spark_connector_jni_MilvusStorageJNI_00024_readPropertiesFree
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_zilliz_spark_connector_jni_MilvusStorageJNI
 * Method:    getChunkIndices
 * Signature: (J[J)[J
 */
JNIEXPORT jlongArray JNICALL Java_com_zilliz_spark_connector_jni_MilvusStorageJNI_00024_getChunkIndices
  (JNIEnv *, jclass, jlong, jlongArray);

/*
 * Class:     com_zilliz_spark_connector_jni_MilvusStorageJNI
 * Method:    getChunk
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_com_zilliz_spark_connector_jni_MilvusStorageJNI_00024_getChunk
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_zilliz_spark_connector_jni_MilvusStorageJNI
 * Method:    getChunks
 * Signature: (J[JJ)[J
 */
JNIEXPORT jlongArray JNICALL Java_com_zilliz_spark_connector_jni_MilvusStorageJNI_00024_getChunks
  (JNIEnv *, jclass, jlong, jlongArray, jlong);

/*
 * Class:     com_zilliz_spark_connector_jni_MilvusStorageJNI
 * Method:    chunkReaderDestroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_zilliz_spark_connector_jni_MilvusStorageJNI_00024_chunkReaderDestroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_zilliz_spark_connector_jni_MilvusStorageJNI
 * Method:    readerNew
 * Signature: (JLjava/lang/String;J[Ljava/lang/String;J)J
 */
JNIEXPORT jlong JNICALL Java_com_zilliz_spark_connector_jni_MilvusStorageJNI_00024_readerNew
  (JNIEnv *, jclass, jlong, jstring, jlong, jobjectArray, jlong);

/*
 * Class:     com_zilliz_spark_connector_jni_MilvusStorageJNI
 * Method:    getRecordBatchReader
 * Signature: (JLjava/lang/String;JJ)J
 */
JNIEXPORT jlong JNICALL Java_com_zilliz_spark_connector_jni_MilvusStorageJNI_00024_getRecordBatchReader
  (JNIEnv *, jclass, jlong, jstring, jlong, jlong);

/*
 * Class:     com_zilliz_spark_connector_jni_MilvusStorageJNI
 * Method:    getChunkReader
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_com_zilliz_spark_connector_jni_MilvusStorageJNI_00024_getChunkReader
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_zilliz_spark_connector_jni_MilvusStorageJNI
 * Method:    take
 * Signature: (J[JJ)J
 */
JNIEXPORT jlong JNICALL Java_com_zilliz_spark_connector_jni_MilvusStorageJNI_00024_take
  (JNIEnv *, jclass, jlong, jlongArray, jlong);

/*
 * Class:     com_zilliz_spark_connector_jni_MilvusStorageJNI
 * Method:    readerDestroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_zilliz_spark_connector_jni_MilvusStorageJNI_00024_readerDestroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_zilliz_spark_connector_jni_MilvusStorageJNI
 * Method:    releaseArrowArray
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_zilliz_spark_connector_jni_MilvusStorageJNI_00024_releaseArrowArray
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_zilliz_spark_connector_jni_MilvusStorageJNI
 * Method:    releaseArrowSchema
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_zilliz_spark_connector_jni_MilvusStorageJNI_00024_releaseArrowSchema
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_zilliz_spark_connector_jni_MilvusStorageJNI
 * Method:    releaseArrowArrayStream
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_zilliz_spark_connector_jni_MilvusStorageJNI_00024_releaseArrowArrayStream
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_zilliz_spark_connector_jni_MilvusStorageJNI
 * Method:    getArrowArrayLength
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_zilliz_spark_connector_jni_MilvusStorageJNI_00024_getArrowArrayLength
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_zilliz_spark_connector_jni_MilvusStorageJNI
 * Method:    getArrowArrayNumChildren
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_zilliz_spark_connector_jni_MilvusStorageJNI_00024_getArrowArrayNumChildren
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
