#!/bin/bash

# Generate JNI Header Script
# This script generates JNI headers for the MilvusStorageJNI class

set -e

# Configuration
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
SCALA_SRC="$PROJECT_ROOT/src/main/scala"
C_SRC="$PROJECT_ROOT/src/main/c"
INCLUDE_DIR="$C_SRC/include"
TARGET_DIR="$PROJECT_ROOT/target"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}Generating JNI headers...${NC}"

# Create include directory if it doesn't exist
mkdir -p "$INCLUDE_DIR"

# Find Java/JDK
if [ -z "$JAVA_HOME" ]; then
    JAVA_HOME=$(dirname $(dirname $(readlink -f $(which java))))
fi

echo -e "${YELLOW}Using JAVA_HOME: $JAVA_HOME${NC}"

# Create header manually
HEADER_FILE="$INCLUDE_DIR/com_zilliz_spark_connector_jni_MilvusStorageJNI.h"

echo -e "${YELLOW}Creating JNI header manually...${NC}"
cat > "$HEADER_FILE" << 'HEADER_EOF'
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zilliz_spark_connector_jni_MilvusStorageJNI */

#ifndef _Included_com_zilliz_spark_connector_jni_MilvusStorageJNI
#define _Included_com_zilliz_spark_connector_jni_MilvusStorageJNI
#ifdef __cplusplus
extern "C" {
#endif


// ==================== Reader C API Methods ====================

/*
 * Class:     com_zilliz_spark_connector_jni_MilvusStorageJNI
 * Method:    readPropertiesDefault
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_zilliz_spark_connector_jni_MilvusStorageJNI_00024_readPropertiesDefault
  (JNIEnv *, jclass);

/*
 * Class:     com_zilliz_spark_connector_jni_MilvusStorageJNI
 * Method:    readPropertiesCreate
 * Signature: ([Ljava/lang/String;[Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_zilliz_spark_connector_jni_MilvusStorageJNI_00024_readPropertiesCreate
  (JNIEnv *, jclass, jobjectArray, jobjectArray);

/*
 * Class:     com_zilliz_spark_connector_jni_MilvusStorageJNI
 * Method:    readPropertiesGet
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_zilliz_spark_connector_jni_MilvusStorageJNI_00024_readPropertiesGet
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_zilliz_spark_connector_jni_MilvusStorageJNI
 * Method:    readPropertiesFree
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_zilliz_spark_connector_jni_MilvusStorageJNI_00024_readPropertiesFree
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_zilliz_spark_connector_jni_MilvusStorageJNI
 * Method:    getChunkIndices
 * Signature: (J[J)[J
 */
JNIEXPORT jlongArray JNICALL Java_com_zilliz_spark_connector_jni_MilvusStorageJNI_00024_getChunkIndices
  (JNIEnv *, jclass, jlong, jlongArray);

/*
 * Class:     com_zilliz_spark_connector_jni_MilvusStorageJNI
 * Method:    getChunk
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_com_zilliz_spark_connector_jni_MilvusStorageJNI_00024_getChunk
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_zilliz_spark_connector_jni_MilvusStorageJNI
 * Method:    getChunks
 * Signature: (J[JJ)[J
 */
JNIEXPORT jlongArray JNICALL Java_com_zilliz_spark_connector_jni_MilvusStorageJNI_00024_getChunks
  (JNIEnv *, jclass, jlong, jlongArray, jlong);

/*
 * Class:     com_zilliz_spark_connector_jni_MilvusStorageJNI
 * Method:    chunkReaderDestroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_zilliz_spark_connector_jni_MilvusStorageJNI_00024_chunkReaderDestroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_zilliz_spark_connector_jni_MilvusStorageJNI
 * Method:    readerNew
 * Signature: (JLjava/lang/String;J[Ljava/lang/String;J)J
 */
JNIEXPORT jlong JNICALL Java_com_zilliz_spark_connector_jni_MilvusStorageJNI_00024_readerNew
  (JNIEnv *, jclass, jlong, jstring, jlong, jobjectArray, jlong);

/*
 * Class:     com_zilliz_spark_connector_jni_MilvusStorageJNI
 * Method:    getRecordBatchReader
 * Signature: (JLjava/lang/String;JJ)J
 */
JNIEXPORT jlong JNICALL Java_com_zilliz_spark_connector_jni_MilvusStorageJNI_00024_getRecordBatchReader
  (JNIEnv *, jclass, jlong, jstring, jlong, jlong);

/*
 * Class:     com_zilliz_spark_connector_jni_MilvusStorageJNI
 * Method:    getChunkReader
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_com_zilliz_spark_connector_jni_MilvusStorageJNI_00024_getChunkReader
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_zilliz_spark_connector_jni_MilvusStorageJNI
 * Method:    take
 * Signature: (J[JJ)J
 */
JNIEXPORT jlong JNICALL Java_com_zilliz_spark_connector_jni_MilvusStorageJNI_00024_take
  (JNIEnv *, jclass, jlong, jlongArray, jlong);

/*
 * Class:     com_zilliz_spark_connector_jni_MilvusStorageJNI
 * Method:    readerDestroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_zilliz_spark_connector_jni_MilvusStorageJNI_00024_readerDestroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_zilliz_spark_connector_jni_MilvusStorageJNI
 * Method:    releaseArrowArray
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_zilliz_spark_connector_jni_MilvusStorageJNI_00024_releaseArrowArray
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_zilliz_spark_connector_jni_MilvusStorageJNI
 * Method:    releaseArrowSchema
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_zilliz_spark_connector_jni_MilvusStorageJNI_00024_releaseArrowSchema
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_zilliz_spark_connector_jni_MilvusStorageJNI
 * Method:    releaseArrowArrayStream
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_zilliz_spark_connector_jni_MilvusStorageJNI_00024_releaseArrowArrayStream
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_zilliz_spark_connector_jni_MilvusStorageJNI
 * Method:    getArrowArrayLength
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_zilliz_spark_connector_jni_MilvusStorageJNI_00024_getArrowArrayLength
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_zilliz_spark_connector_jni_MilvusStorageJNI
 * Method:    getArrowArrayNumChildren
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_zilliz_spark_connector_jni_MilvusStorageJNI_00024_getArrowArrayNumChildren
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
HEADER_EOF

# Verify header file exists
if [ -f "$HEADER_FILE" ]; then
    echo -e "${GREEN}JNI header generated successfully: $HEADER_FILE${NC}"
else
    echo -e "${RED}Failed to generate JNI header${NC}"
    exit 1
fi

echo -e "${GREEN}JNI header generation complete${NC}"
